vsphere_user           = "email"
vsphere_password       = "password"
vsphere_server         = "vcenter.netlab.fontysict.nl"
vm_name               = "nginx-server"
vm_ipv4_address       = "192.168.154.138"
vm_ipv4_gateway       = "192.168.154.1"
vm_network            = "bn"
vm_template           = "Ubuntu-Template"